import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import styles from '../styles/Home.module.scss'

import socialIcons from "../JSON/socialIcons"

export default function Home() {
  const socials = socialIcons.message
  const iconSocialSize = 45

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Maxim Belyakov</h1>
        <p className={styles.lead}>Creating is my passion. Being better than yesterday really makes me happy.</p>
        <p className={styles.quote}>Life is 10% what happens to you and 90% how you react to it.</p>
        <p className={styles.emoji}>
          <span role="img" aria-label="rocket">🚀</span>
          <span role="img" aria-label="alien">👽</span>
          <span role="img" aria-label="alien-monster">👾</span>
        </p>
        <section>
          <h2 className={styles.check}>
            <Link href="/portfolio">Portfolio projects</Link>
          </h2>
        </section>
        <section className={styles.socials}>
          {/*{socials.map((social, i) => (*/}
          {/*    <SocialIcon key={i} bgColor="#222222" target="_blank" style={{ height: iconSocialSize, width: iconSocialSize }} network={social.name} url={social.link} />*/}
          {/*))}*/}
        </section>
      </main>
    </div>
  )
}
