name: Deploy Next.js Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn build

      - name: Export static files
        run: yarn static

      - name: Create website archive
        run: |
          cd out
          zip -r ../website.zip . -x "*.git*"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 -H 89.108.64.127 >> ~/.ssh/known_hosts

      - name: Upload and deploy archive
        run: |
          scp -P 22 website.zip deploy@89.108.64.127:/tmp/
          ssh -p 22 deploy@89.108.64.127 'cd /var/www/belyakov.site/ && rm -rf * .* 2>/dev/null || true && unzip -o /tmp/website.zip -d . && rm /tmp/website.zip'
